name: CI|CD Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Running backend and testing
        run: |
          cd backend
          node server.js &
          sleep 3
          curl http://localhost:5000

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Building frontend
        run: |
          cd frontend
          npm run build
